---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yml
  - selenium.yml

configMapGenerator:
  - name: env
    literals:
      - GCROSTORE_HOST=gcrostore.default.svc.cluster.local
      - SELENIUM_HOST=selenium
  - name: scripts
    files:
      - scripts/cancel-sold-items.sh
      - scripts/request-login.sh
