---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcrostore
  annotations:
    kube-score/ignore: |
      container-security-context-user-group-id,
      pod-networkpolicy,
spec:
  selector:
    matchLabels:
      app: gcrostore
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: gcrostore
    spec:
      containers:
        - name: gcrostore
          image: ghcr.io/huisint/gcrostore:0.0.7
          imagePullPolicy: Always
          env:
            - name: SMTP_HOST
              value: postfix.default.svc.cluster.local
            - name: SMTP_PORT
              value: '25'
            - name: SMTP_FROM
              value: Crostore <ecoreuse9@gmail.com>
            - name: CROSTORE_SELENIUM_WAIT
              value: '30'
          ports:
            - containerPort: 8080
          command:
            - uvicorn
            - gcrostore:app
            - --host=0.0.0.0
            - --port=8080
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
              ephemeral-storage: 512Mi
            requests:
              memory: 128Mi
              cpu: 200m
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: gcrostore
spec:
  selector:
    app: gcrostore
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gcrostore
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gcrostore
