---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cancel-sold-items
  annotations:
    kube-score/ignore: |
      container-security-context-user-group-id,
      pod-networkpolicy,
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:8.00.1
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: script-env
                - secretRef:
                    name: script-secret
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              resources:
                limits:
                  memory: 256Mi
                  cpu: 250m
                  ephemeral-storage: 256Mi
              securityContext:
                readOnlyRootFilesystem: true
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              command:
                - sh
                - -c
                - |
                  while (true); do
                    sh -x /scripts/cancel-sold-items.sh
                    if [ ! $? -eq 6 ]; then
                      break
                    fi
                  done
          volumes:
            - name: scripts
              configMap:
                name: scripts
                defaultMode: 0775
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: request-login
  annotations:
    kube-score/ignore: |
      container-security-context-user-group-id,
      pod-networkpolicy,
spec:
  schedule: 0 12 * * *
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:8.00.1
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: script-env
                - secretRef:
                    name: script-secret
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              resources:
                limits:
                  memory: 256Mi
                  cpu: 250m
                  ephemeral-storage: 256Mi
              securityContext:
                readOnlyRootFilesystem: true
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              command:
                - sh
                - -c
                - |
                  while (true); do
                    sh -x /scripts/request-login.sh
                    if [ ! $? -eq 6 ]; then
                      break
                    fi
                  done
          volumes:
            - name: scripts
              configMap:
                name: scripts
                defaultMode: 0775
          restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-env
data:
  GCROSTORE_HOST: gcrostore.default.svc.cluster.local
  SELENIUM_HOST: selenium
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: script-secret
# type: Opaque
# data:
#   USER_NAME: ''
#   USER_EMAIL: ''
#   GOOGLE_SHEET_ID: ''
#   SELENIUM_DESIRED_CAPABILITIES: ''
#   GOOGLE_CREDENTIALS: ''
