---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yml
  - selenium.yml

configMapGenerator:
  - name: scripts
    files:
      - scripts/cancel-sold-items.sh
      - scripts/request-login.sh
