---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcrostore
  annotations:
    kube-score/ignore: |
      container-security-context-user-group-id,
      pod-networkpolicy,
spec:
  selector:
    matchLabels:
      app: gcrostore
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: gcrostore
    spec:
      containers:
        - name: gcrostore
          image: ghcr.io/huisint/gcrostore:0.0.9
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: gcrostore-env
          ports:
            - containerPort: 8080
          command:
            - uvicorn
            - gcrostore:app
            - --host=0.0.0.0
            - --port=8080
            - --log-config=/config/logging-config.yml
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
              ephemeral-storage: 512Mi
            requests:
              memory: 128Mi
              cpu: 200m
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: gcrostore-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcrostore-env
data:
  SMTP_HOST: postfix.default.svc
  SMTP_PORT: '25'
  SMTP_FROM: Crostore <ecoreuse9@gmail.com>
  CROSTORE_SELENIUM_WAIT: '30'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcrostore-config
data:
  logging-config.yml: |
    version: 1
    formatters:
      default:
        '()': uvicorn.logging.DefaultFormatter
        fmt: '%(levelprefix)s %(message)s'
        use_colors: null
      access:
        '()': uvicorn.logging.AccessFormatter
        fmt: >
          '%(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
    handlers:
      default:
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stderr
      access:
        class: logging.StreamHandler
        formatter: access
        stream: ext://sys.stdout
    loggers:
      crostore:
        handlers:
          - default
        level: DEBUG
      gcrosotre:
        handlers:
          - default
        level: DEBUG
      uvicorn.error:
        handlers:
          - default
        level: INFO
      uvicorn.access:
        handlers:
          - access
        level: INFO
---
apiVersion: v1
kind: Service
metadata:
  name: gcrostore
spec:
  selector:
    app: gcrostore
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gcrostore
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: gcrostore
