---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  annotations:
    kube-score/ignore: |
      container-security-context-readonlyrootfilesystem,
      container-security-context-user-group-id,
      pod-networkpolicy,
spec:
  selector:
    matchLabels:
      app: postfix
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
        - name: postfix
          image: juanluisbaptiste/postfix:1.7.1
          imagePullPolicy: Always
          env:
            - name: SERVER_HOSTNAME
              value: crostore.com
            - name: SMTP_SERVER
              value: smtp.gmail.com
            - name: SMTP_PORT
              value: '587'
            - name: SMTP_USERNAME
              value: ecoreuse9@gmail.com
          envFrom:
            - secretRef:
                name: postfix
          ports:
            - containerPort: 25
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
              ephemeral-storage: 256Mi
            requests:
              memory: 128Mi
              cpu: 100m
          securityContext:
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 25
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: postfix
spec:
  selector:
    app: postfix
  ports:
    - port: 25
      targetPort: 25
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postfix
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: postfix
